### ISSUE TITLE
Drop ANSI color emulation on Windows

### ISSUE THREAD

**Issue by thekid** [xp-runners/reference#53]
According to [this blog](http://www.nivot.org/blog/post/2016/02/04/Windows-10-TH2-%28v1511%29-Console-Host-Enhancements) from February 2016, ANSI escape sequences work natively on Windows Console since Windows 10 build 10586. Proof:

![console-color-windows-cmd](https://cloud.githubusercontent.com/assets/696742/16126138/2eb864ec-33f7-11e6-91a2-cd77a1787c3c.png)

I suggest we drop the emulation from the XP runners. To those with Windows 7: **Upgrade!**

See also https://godoc.org/github.com/buger/goterm and http://www.darkcoding.net/software/pretty-command-line-console-output-on-unix-in-python-and-go-lang/

/cc @kiesel

**Comment by kiesel** [comment]
Dropping code is always good:) Only that it just works for Windows 10 is a bit sad.

**Comment by thekid** [comment]
As stated above:

> To those with Windows 7: Upgrade!

😊
