### ISSUE TITLE
Bintray will be sunset, find new Debian package repo

### ISSUE THREAD

**Issue by thekid** [xp-runners/reference#81]
Mail from March 31st:

> As we noted previously, as of May 1, 2021 we will be sunsetting Bintray. Many of the services that Bintray provides are now served by the JFrog Platform and this sunset allows us to focus our development and innovation efforts on building a comprehensive end-to-end solution for hosting and distribution of software artifacts. 

Can we use GitHub?

**Comment by mattfox** [comment]
You can use GitHub to host plain .deb files, but then you can't install or upgrade with apt on Debian/Ubuntu. So it's not a great experience for users.

You're welcome to try my service as an alternative to Bintray- Balto Repo- https://www.getbalto.com/

**Comment by thekid** [comment]
https://www.gitmemory.com/issue/i3/i3/4340/778492865

**Comment by thekid** [comment]
Here's an initial implementation, however, because Balto's task queue seem to be be down (*published first release @ 17 Apr 2021 13:13:56 GMT, more than 45 minutes ago at the time of writing*), I can't verify it actually works:

```diff
diff --git a/debian.sh b/debian.sh
index df65796..e8be194 100755
--- a/debian.sh
+++ b/debian.sh
@@ -14,13 +14,13 @@ BUILD=$(mktemp -d)
 ORIGIN=$(pwd)
 TARGET=$ORIGIN/target
 DEB=$TARGET/xp-runners_${VERSION}-1_all.deb
-BINTRAY=$TARGET/debian.config
 
 echo "Creating package $DEB in $BUILD"
+cp README.md $BUILD
 
 mkdir -p target
-rm -f $DEB $BINTRAY
-fakeroot=$(which fakeroot || which fakeroot-ng)
+rm -f $DEB
+fakeroot=$(which fakeroot || which fakeroot-ng || eval)
 cd $BUILD
 
 echo '2.0' > debian-binary
@@ -56,40 +56,17 @@ EOF
 $fakeroot tar cfz control.tar.gz conffiles control
 cat control
 
-ar -q $DEB debian-binary control.tar.gz data.tar.xz
+ar -q $DEB debian-binary control.tar.gz data.tar.xz control
 
-# Bintray configuration
-date=$(date +%Y-%m-%d)
-cat <<-EOF > $BINTRAY
-	{
-	  "package": {
-	    "name"     : "xp-runners",
-	    "repo"     : "debian",
-	    "subject"  : "xp-runners"
-	  },
-	  "version": {
-	    "name"     : "${VERSION}",
-	    "desc"     : "XP Runners release ${VERSION}",
-	    "released" : "${date}",
-	    "vcs_tag"  : "${TRAVIS_TAG}",
-	    "gpgSign"  : true
-	  },
-	  "files": [
-	    {
-	      "includePattern" : "target/(xp-runners.*deb)",
-	      "uploadPattern"  : "\$1",
-	      "matrixParams"   : {
-	        "deb_distribution" : "jessie",
-	        "deb_component"    : "main",
-	        "deb_architecture" : "i386,amd64",
-	        "override"         : 1
-	      }
-	    }
-	  ],
-	  "publish": true
-	}
-EOF
+# Publish to Balto
+curl --verbose \
+  --header "Authorization: Bearer ${BALTO_REPO_TOKEN}" \
+  --form "package=@${DEB}" \
+  --form "distribution=all" \
+  --form "readme=<README.md" \
+  https://xp.baltorepo.com/xp-runners/reference/upload/
+echo
 
 # Done
 rm -rf $BUILD
-ls -al $DEB $BINTRAY
\ No newline at end of file
+ls -al $DEB
\ No newline at end of file
```

The results should eventually show up at https://xp.baltorepo.com/xp-runners/reference/

**Comment by thekid** [comment]
Balto is looking good:

![image](https://user-images.githubusercontent.com/696742/115122605-0b29ff80-9fb9-11eb-903c-0afc9057531a.png)

https://xp.baltorepo.com/xp-runners/

**Comment by thekid** [comment]
Migrated in https://github.com/xp-runners/reference/releases/tag/v8.5.0, see https://travis-ci.org/github/xp-runners/reference/builds/767410600#L1226 and following
